name: "synchronize-pr-and-asana"
on:
  pull_request:

jobs:
  synchronize-pr-and-asana:
    runs-on: ubuntu-latest
    steps:
    - uses: H37kouya/synchronize-pr-and-asana@alpha
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        asana-token: "${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}"
        custom-fields: ""